In [1]:
import pandas as pd
import json

playlist = json.load(open('mpd.slice.1000-1999.json'))


df = pd.json_normalize(playlist['playlists'], 'tracks', 
                  [
                      'name', 
                      'collaborative',
                      'pid',
                      'modified_at',
                      'num_tracks',
                      'num_albums',
                      'num_followers',
                      'num_edits',
                      'duration_ms',
                      'num_artists'
                  ],
                  meta_prefix='playlist_'
)
df

,pos,artist_name,track_uri,artist_uri,track_name,album_uri,duration_ms,album_name,playlist_name,playlist_collaborative,playlist_pid,playlist_modified_at,playlist_num_tracks,playlist_num_albums,playlist_num_followers,playlist_num_edits,playlist_duration_ms,playlist_num_artists
0,0,Original Broadway Cast - The Little Mermaid,spotify:track:5IbCV9Icebx8rR6wAp5hhP,spotify:artist:3TymzPhJTMyupk7P5xkahM,Fathoms Below - Broadway Cast Recording,spotify:album:3ULJeOMgroG27dpn27MDfS,154506,The Little Mermaid: Original Broadway Cast Rec...,disney,false,1000,1457827200,189,16,1,4,31428282,65
1,1,Original Broadway Cast - The Little Mermaid,spotify:track:6rKVAvjHcxAzZ1BHtwh5yC,spotify:artist:3TymzPhJTMyupk7P5xkahM,Daughters Of Triton - Broadway Cast Recording,spotify:album:3ULJeOMgroG27dpn27MDfS,79066,The Little Mermaid: Original Broadway Cast Rec...,disney,false,1000,1457827200,189,16,1,4,31428282,65
2,2,Original Broadway Cast - The Little Mermaid,spotify:track:6Jlkb1Wh08RYHstWScsTvg,spotify:artist:3TymzPhJTMyupk7P5xkahM,The World Above - Broadway Cast Recording,spotify:album:3ULJeOMgroG27dpn27MDfS,94600,The Little Mermaid: Original Broadway Cast Rec...,disney,false,1000,1457827200,189,16,1,4,31428282,65
3,3,Original Broadway Cast - The Little Mermaid,spotify:track:0XhC8bfStML9ygBmfOt1JJ,spotify:artist:3TymzPhJTMyupk7P5xkahM,Human Stuff - Broadway Cast Recording,spotify:album:3ULJeOMgroG27dpn27MDfS,151480,The Little Mermaid: Original Broadway Cast Rec...,disney,false,1000,1457827200,189,16,1,4,31428282,65
4,4,Original Broadway Cast - The Little Mermaid,spotify:track:0ABxAcsRWlqckkyONsfP67,spotify:artist:3TymzPhJTMyupk7P5xkahM,I Want the Good Times Back - Broadway Cast Rec...,spotify:album:3ULJeOMgroG27dpn27MDfS,297920,The Little Mermaid: Original Broadway Cast Rec...,disney,false,1000,1457827200,189,16,1,4,31428282,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66617,11,Seether,spotify:track:2G8gLafzmoHwa6RBih74J3,spotify:artist:6B5c4sch27tWHAGdarpPaW,Broken - Featuring Amy Lee,spotify:album:5qHjA0aU9vt9c2UwDeEGjS,258333,Disclaimer II,Sad Music,false,1999,1464307200,16,14,1,3,3701742,12
66618,12,Three Days Grace,spotify:track:1bPRhOz3nOfEIoLjB1YYT3,spotify:artist:2xiIXseIJcq3nG7C8fHeBj,No More,spotify:album:0vv1zKShlm7WuawEup5Mf4,225493,Life Starts Now,Sad Music,false,1999,1464307200,16,14,1,3,3701742,12
66619,13,Three Days Grace,spotify:track:1o4Pf2GIMDCD7ifIM2yI77,spotify:artist:2xiIXseIJcq3nG7C8fHeBj,Last to Know,spotify:album:0vv1zKShlm7WuawEup5Mf4,207466,Life Starts Now,Sad Music,false,1999,1464307200,16,14,1,3,3701742,12
66620,14,3 Doors Down,spotify:track:0nNVR2iDM3eVzEgMi78vQm,spotify:artist:2RTUTCvo6onsAnheUk3aL9,Let Me Go,spotify:album:44AVPs6VGKnZHinQNWd6Xd,243053,The Greatest Hits,Sad Music,false,1999,1464307200,16,14,1,3,3701742,12
66621,15,Tech N9ne Collabos,spotify:track:6XzJXUQpwPkp8g5KW9TRoP,spotify:artist:4UOlRVifrFdQHW9qu5ep8t,Actin Like You Know,spotify:album:3WyX9z5XQxk8X5HZdnbzJi,239928,Strangeulation Vol. II (Deluxe Edition),Sad Music,false,1999,1464307200,16,14,1,3,3701742,12

In [2]:
df_playlist = (df.loc[:,['playlist_pid', 
          'playlist_name', 
          'playlist_collaborative', 
          'playlist_modified_at',
         'playlist_num_followers',
         'playlist_num_edits']]
 .drop_duplicates()
 .reset_index()
 .rename(columns={
     'index': 'sk_id',
     'playlist_pid': 'bk_id', 
          'playlist_name': 'name', 
          'playlist_collaborative': 'collaborative', 
          'playlist_modified_at': 'last_modified_at',
         'playlist_num_followers': 'num_followers',
         'playlist_num_edits': 'num_edits'
 })
 .assign(sk_id = lambda d: d.index+1,
        last_modified_at = lambda df: pd.to_datetime(df.last_modified_at, unit='s'))
)
df_playlist

,sk_id,bk_id,name,collaborative,last_modified_at,num_followers,num_edits
0,1,1000,disney,false,2016-03-13,1,4
1,2,1001,Indie Electro,false,2014-12-06,2,2
2,3,1002,jack & jack,false,2016-06-09,1,3
3,4,1003,vibes,false,2017-06-26,2,91
4,5,1004,Indie,false,2017-06-28,1,74
...,...,...,...,...,...,...,...
995,996,1995,woo,false,2017-10-27,2,13
996,997,1996,NEW YEARS,false,2015-01-01,1,3
997,998,1997,JESUS,false,2017-10-19,2,8
998,999,1998,yep,false,2015-11-23,1,3
999,1000,1999,Sad Music,false,2016-05-27,1,3

In [3]:
from sqlalchemy import create_engine

target = create_engine('postgresql+psycopg2://test:test123@localhost:5432/spotify_test')

In [4]:
df_playlist.to_sql('d_playlists', con=target, index=False, if_exists='append')

1000

In [5]:
df_tracks = (df.loc[:,['track_uri', 
          'track_name', 
          'duration_ms']]
 .drop_duplicates()
 .reset_index()
 .rename(columns={
     'index': 'sk_id',
     'track_uri': 'bk_id', 
          'track_name': 'name', 
          'duration_ms': 'duration'
 })
 .assign(sk_id = lambda d: d.index+1)
)
df_tracks

,sk_id,bk_id,name,duration
0,1,spotify:track:5IbCV9Icebx8rR6wAp5hhP,Fathoms Below - Broadway Cast Recording,154506
1,2,spotify:track:6rKVAvjHcxAzZ1BHtwh5yC,Daughters Of Triton - Broadway Cast Recording,79066
2,3,spotify:track:6Jlkb1Wh08RYHstWScsTvg,The World Above - Broadway Cast Recording,94600
3,4,spotify:track:0XhC8bfStML9ygBmfOt1JJ,Human Stuff - Broadway Cast Recording,151480
4,5,spotify:track:0ABxAcsRWlqckkyONsfP67,I Want the Good Times Back - Broadway Cast Rec...,297920
...,...,...,...,...
36170,36171,spotify:track:2c5wml8wsBnPfNSbCZ574T,Take a Picture,359520
36171,36172,spotify:track:3bq8WiQrEXMwPAibYs7tpu,Nobody Praying For Me,197800
36172,36173,spotify:track:1bPRhOz3nOfEIoLjB1YYT3,No More,225493
36173,36174,spotify:track:1o4Pf2GIMDCD7ifIM2yI77,Last to Know,207466
36174,36175,spotify:track:6XzJXUQpwPkp8g5KW9TRoP,Actin Like You Know,239928

In [6]:
df_tracks.to_sql('d_tracks', con=target, index=False, if_exists='append')

175

In [7]:
df_artist = (df.loc[:,['artist_uri', 
          'artist_name']]
 .drop_duplicates()
 .reset_index()
 .rename(columns={
     'index': 'sk_id',
     'artist_uri': 'bk_id', 
          'artist_name': 'name'
 })
 .assign(sk_id = lambda d: d.index+1)
)
df_artist

,sk_id,bk_id,name
0,1,spotify:artist:3TymzPhJTMyupk7P5xkahM,Original Broadway Cast - The Little Mermaid
1,2,spotify:artist:1j4a3bBWYNjecFqxcjRtr5,Sierra Boggess as Ariel
2,3,spotify:artist:5sy77gt4bfsLcSQ8GIe4ZZ,Alan Menken
3,4,spotify:artist:1RJ9qwSsCfnOcTXBSqotNk,Ariel
4,5,spotify:artist:6Id8rcDNyBXPcgKQVfQ8rX,Samuel E. Wright
...,...,...,...
10298,10299,spotify:artist:3tM6SwRysCaIK0kW4h0mVP,Spose
10299,10300,spotify:artist:4qUFkkArfii3qNG8TnbPfc,Masked Intruder
10300,10301,spotify:artist:7C64wNX3howEFZjAYRKsfP,The Cataracs
10301,10302,spotify:artist:6pxwzi0xDny2rMI1KJFZoi,Young T.H.U.G.
10302,10303,spotify:artist:2HHIJKrqm8CEnlKlv5gIHI,The Royal Viena Orchestra

In [8]:
df_artist.to_sql('d_artists', con=target, index=False, if_exists='append')

303

In [9]:
df_album = (df.loc[:,['album_uri', 
          'album_name']]
 .drop_duplicates()
 .reset_index()
 .rename(columns={
     'index': 'sk_id',
     'album_uri': 'bk_id', 
          'album_name': 'name'
 })
 .assign(sk_id = lambda d: d.index+1)
)
df_album

,sk_id,bk_id,name
0,1,spotify:album:3ULJeOMgroG27dpn27MDfS,The Little Mermaid: Original Broadway Cast Rec...
1,2,spotify:album:4aAwvCRNJIqiUGVEjieWv6,Little Mermaid
2,3,spotify:album:5wqx6PBsow0KIQrnu9xd6c,Aladdin Original Broadway Cast Recording
3,4,spotify:album:6fBzYwBKjuO4hmhcGuklJM,Tarzan Original Soundtrack
4,5,spotify:album:6DnTzVKb79zEtICWeIB2El,Beauty And The Beast: The Broadway Musical
...,...,...,...
20207,20208,spotify:album:5UnaAIuMRqSBeBWY3XM0FQ,American Prodigal
20208,20209,spotify:album:77yXUMeh96foFhIR2aK3Fb,De Cine
20209,20210,spotify:album:3nta4nhqWoWjc6LmHIB0kT,Verities & Balderdash
20210,20211,spotify:album:5G6pS4ES22Np0hehqJYIct,Title Of Record
20211,20212,spotify:album:3WyX9z5XQxk8X5HZdnbzJi,Strangeulation Vol. II (Deluxe Edition)

In [10]:
df_album.to_sql('d_albums', con=target, index=False, if_exists='append')

212

In [11]:
df_f_playlist = (df
 .merge(df_playlist.loc[:,['sk_id', 'bk_id']], 
       left_on='playlist_pid', 
       right_on='bk_id', 
       how='inner',
       suffixes=('','_d_playlist'))
 .merge(df_tracks.loc[:,['sk_id', 'bk_id']],
       left_on='track_uri', 
       right_on='bk_id', 
       how='inner',
       suffixes=('_d_playlists','_d_tracks'))
 .merge(df_artist.loc[:,['sk_id', 'bk_id']],
       left_on='artist_uri', 
       right_on='bk_id', 
       how='inner',
       suffixes=('','_d_artist'))
  .merge(df_album.loc[:,['sk_id', 'bk_id']],
       left_on='album_uri', 
       right_on='bk_id', 
       how='inner',
       suffixes=('_d_artist','_d_album'))
 .loc[:,['sk_id_d_playlists',
        'sk_id_d_artist',
        'sk_id_d_album',
        'sk_id_d_tracks',
        'pos']]
 .rename(columns={
     "sk_id_d_playlists": "sk_playlist",
     "sk_id_d_artist": "sk_artist",
     "sk_id_d_album": "sk_album",
     "sk_id_d_tracks": "sk_track",
     "pos": "track_position"
 })
 .assign(id = lambda df: df.index+1)
)
df_f_playlist

       sk_playlist  sk_artist  sk_album  sk_track  track_position     id
0                1          1         1         1               0      1
1                1          1         1         2               1      2
2                1          1         1         3               2      3
3                1          1         1         4               3      4
4                1          1         1         5               4      5
...            ...        ...       ...       ...             ...    ...
66617          996      10300     20194     36141             137  66618
66618          996      10300     20197     36144             145  66619
66619          997      10301     20199     36147              22  66620
66620          997      10302     20202     36150              35  66621
66621          999      10303     20209     36169               1  66622

[66622 rows x 6 columns]

In [12]:
df_f_playlist.to_sql('f_playlist_tracks', con=target, index=False, if_exists='append')

622